name: 'Upload PR Comment Data'
description: 'Creates and uploads PR comment data as an artifact for later posting'
inputs:
  message-file:
    description: 'Path to file containing the comment message'
    required: true
  message-id:
    description: 'Unique identifier for the comment (used for updating existing comments)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare PR comment data
      shell: bash
      run: |
        if [ ! -f "${{ inputs.message-file }}" ]; then
          echo "Message file ${{ inputs.message-file }} not found, skipping PR comment"
          exit 0
        fi
        
        message=$(cat "${{ inputs.message-file }}")
        cat > pr-comment.json << 'EOF'
        {
          "pr-number": ${{ github.event.number }},
          "message-id": "${{ inputs.message-id }}",
          "message": $(echo "$message" | jq -Rs .)
        }
        EOF

    - name: Upload PR comment data
      uses: actions/upload-artifact@v4
      with:
        name: pr-comment-data
        path: pr-comment.json
        retention-days: 1