name: Package dependencies

on:
  workflow_call:

jobs:
  check-dependency:
    name: Check dependency
    runs-on: ubuntu-latest
    if: |
      startswith(github.event_name, 'pull_request') &&
      startswith(github.base_ref, 'ubuntu-')
    env:
      branch: ${{ github.base_ref }}
      main-branch-path: files-from-main
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Check changed paths
        id: changed-paths
        uses: dorny/paths-filter@v3
        with:
          # ref: https://github.com/marketplace/actions/paths-changes-filter
          filters: |
            slices:
              - added|modified: 'slices/**/*.yaml'
          # Space delimited list usable as command-line argument list in
          # Linux shell. If needed, it uses single or double quotes to
          # wrap filename with unsafe characters.
          list-files: shell

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: ${{ env.main-branch-path }}

      - name: Check dependencies
        id: check-deps
        env:
          script-dir: "${{ env.main-branch-path }}/.github/scripts/pkg-deps"
        run: |
          set -ex
          ./${{ env.script-dir }}/pkg-deps \
            ${{ steps.changed-paths.outputs.slices_files }}

      - name: Set PR number
        id: pr-number
        run: |
          # In workflow_call context triggered by pull_request, use the PR number from github context
          echo "result=${{ github.event.number }}" >> $GITHUB_OUTPUT

      - name: Prepare PR comment data
        if: always() && steps.check-deps.outputs.msg_file && steps.pr-number.outputs.result != ''
        run: |
          message=$(cat "${{ steps.check-deps.outputs.msg_file }}")
          cat > pr-comment.json << 'EOF'
          {
            "pr-number": ${{ steps.pr-number.outputs.result }},
            "message-id": "pkg-deps-check",
            "message": $(echo "$message" | jq -Rs .)
          }
          EOF

      - name: Upload PR comment data
        if: always() && steps.check-deps.outputs.msg_file && steps.pr-number.outputs.result != ''
        uses: actions/upload-artifact@v4
        with:
          name: pr-comment-data
          path: pr-comment.json
          retention-days: 1
