name: Package dependencies comment

on:
  workflow_run:
    workflows: ["Pkg coverage"]
    types:
      - completed

jobs:
  post-comment:
    name: Post PR comment
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion != 'skipped'
    permissions:
      pull-requests: write
    steps:
      - name: Download artifact
        uses: actions/github-script@v7
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "pr-comment-message"
            })[0];
            if (!matchArtifact) {
              console.log('No pr-comment-message artifact found');
              return;
            }
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/pr-comment.zip`, Buffer.from(download.data));

      - name: Extract artifact
        run: |
          if [ -f pr-comment.zip ]; then
            unzip pr-comment.zip
            ls -la
          else
            echo "No artifact found, skipping comment"
            exit 0
          fi

      - name: Get PR number
        id: pr-number
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.payload.workflow_run.head_repository.owner.login}:${context.payload.workflow_run.head_branch}`,
              state: 'open'
            });
            
            if (pullRequests.length === 0) {
              console.log('No open PR found for this branch');
              return '';
            }
            
            return pullRequests[0].number;

      - name: Post comment to PR
        if: steps.pr-number.outputs.result != ''
        uses: mshick/add-pr-comment@v2
        with:
          message-path: "*.txt"
          issue: ${{ steps.pr-number.outputs.result }}